name: deblur3d
channels: [conda-forge, pytorch, defaults]
dependencies:
  - python=3.10
  - pytorch=1.12
  - cudatoolkit=11.3
  - numpy=1.26.4
  - scipy<1.13
  - tifffile
  - matplotlib
  - tqdm
  - pip
  - pip:
      - napari[all]
